// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package gateways

import (
	"context"
	"github.com/mtoku/clarc/app/infrastructure"
)

// Injectors from wire.go:

func InitializeUserRepository(constr infrastructure.DBConnectionString, ctx context.Context) (UserRepository, error) {
	db, err := infrastructure.NewDB(constr)
	if err != nil {
		return UserRepository{}, err
	}
	userRepository := NewUserRepository(ctx, db)
	return userRepository, nil
}

func InitializeInMemoryUserRepository() (InMemoryUserRepository, error) {
	inMemoryUserRepository := NewInMemoryUserRepository()
	return inMemoryUserRepository, nil
}
