// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package mock

import (
	"github.com/mtoku/di/users"
)

// Injectors from wire.go:

func InitializeInMemoryUserRepository() (users.IUserRepository, error) {
	iUserRepository := NewInMemoryUserRepository()
	return iUserRepository, nil
}
