// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package service

import (
	"context"
	"github.com/google/wire"
	"github.com/mtoku/di/app/gateways"
	"github.com/mtoku/di/app/infrastructure"
)

// Injectors from wire.go:

func InitializeUserCreateService(constr infrastructure.DBConnectionString, ctx context.Context) (UserCreateService, error) {
	userRepository, err := gateways.InitializeUserRepository(constr, ctx)
	if err != nil {
		return UserCreateService{}, err
	}
	userCreateService := NewUserCreateService(userRepository)
	return userCreateService, nil
}

// wire.go:

var UserCreateServiceSet = wire.NewSet(NewUserCreateService, wire.Bind(new(gateways.IUserRepository), new(gateways.UserRepository)), gateways.InitializeUserRepository)
