// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package service

import (
	"context"
	"github.com/mtoku/di/app/gateways"
	"github.com/mtoku/di/app/infrastructure"
)

// Injectors from wire.go:

func InitializeUserCreateService(constr infrastructure.DBConnectionString, ctx context.Context) (IUserCreateService, error) {
	iUserRepository, err := gateways.InitializeUserRepository(constr, ctx)
	if err != nil {
		return nil, err
	}
	iUserCreateService := NewUserCreateService(iUserRepository)
	return iUserCreateService, nil
}
