// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package user

import (
	"context"
	"github.com/mtoku/di/app/com/domain/app/user"
	"github.com/mtoku/di/app/infrastructure"
)

// Injectors from wire.go:

func InitializeUserController(constr infrastructure.DBConnectionString, ctx context.Context) (UserController, error) {
	iUserCreateService, err := user.InitializeUserCreateService(constr, ctx)
	if err != nil {
		return UserController{}, err
	}
	userController := NewUserController(iUserCreateService)
	return userController, nil
}
