// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package user

import (
	"context"
	"github.com/google/wire"
	"github.com/mtoku/clarc/app/domain/service/user"
	"github.com/mtoku/clarc/app/infrastructure"
	user2 "github.com/mtoku/clarc/app/usecase/user"
)

// Injectors from wire.go:

func InitializeUserController(constr infrastructure.DBConnectionString, ctx context.Context) (UserController, error) {
	userCreateService, err := user.InitializeUserCreateService(constr, ctx)
	if err != nil {
		return UserController{}, err
	}
	userController := NewUserController(userCreateService)
	return userController, nil
}

// wire.go:

var UserControllerSet = wire.NewSet(NewUserController, wire.Bind(new(user2.IUserCreateService),
	new(user.UserCreateService)), user.InitializeUserCreateService)
