// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package user

import (
	"context"
	"github.com/google/wire"
	"github.com/mtoku/clarc/app/com/domain/service"
	"github.com/mtoku/clarc/app/com/usecase"
	"github.com/mtoku/clarc/app/infrastructure"
)

// Injectors from wire.go:

func InitializeUserController(constr infrastructure.DBConnectionString, ctx context.Context) (UserController, error) {
	userCreateService, err := service.InitializeUserCreateService(constr, ctx)
	if err != nil {
		return UserController{}, err
	}
	userController := NewUserController(userCreateService)
	return userController, nil
}

// wire.go:

var UserControllerSet = wire.NewSet(NewUserController, wire.Bind(new(usecase.IUserCreateService),
	new(service.UserCreateService)), service.InitializeUserCreateService)
