// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package user

import (
	"context"
	"github.com/google/wire"
	"github.com/mtoku/clarc/app/gateways/user"
	"github.com/mtoku/clarc/app/infrastructure"
)

// Injectors from wire.go:

func InitializeUserCreateService(constr infrastructure.DBConnectionString, ctx context.Context) (UserCreateService, error) {
	userRepository, err := user.InitializeUserRepository(constr, ctx)
	if err != nil {
		return UserCreateService{}, err
	}
	userCreateService := NewUserCreateService(userRepository)
	return userCreateService, nil
}

// wire.go:

var UserCreateServiceSet = wire.NewSet(NewUserCreateService, wire.Bind(new(user.IUserRepository), new(user.UserRepository)), user.InitializeUserRepository)
