[mysql]
dbname = "clarc"
user   = "admin"
pass   = "pass"
host   = "localhost"
port    = 3306
sslmode = "false"

[psql]
dbname = "clarc"
user   = "admin"
pass   = "pass"
host   = "localhost"
port    = 5432
sslmode = "disable"
blacklist = []