version: '3'
services:
  clarc-app:
    build:
      context: ./docker/golang
      dockerfile: Dockerfile
      args:
        - VARIANT=1.15
        - INSTALL_NODE=true
        - NODE_VERSION=lts/*
    container_name: clarc-app
    volumes:
      - ../:/go/src
    working_dir: /go/src
    tty: true
    stdin_open: true
    command: /bin/bash
  clarc-mysql:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    container_name: clarc-mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_DATABASE: clarc
      MYSQL_USER: admin
      MYSQL_PASSWORD: pass
    volumes:
      - ./var/mysqldb:/var/lib/mysql
  # clarc-postgresql:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.postgresql
  #   container_name: clarc-postgresql
  #   network_mode: bridge
  #   ports:
  #     - '5432:5432'
  #   environment:
  #     POSTGRES_DB: clarc
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: pass
  #   volumes:
  #     - ./var/postgresql:/var/lib/postgresql/data
  #     - ./postgresql:/docker-entrypoint-initdb.d
