// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package users

import (
	"context"
)

import (
	_ "github.com/go-sql-driver/mysql"
)

// Injectors from wire.go:

func InitializeUserRepository(constr DBConnectionString, ctx context.Context) (IUserRepository, error) {
	db, err := NewDB(constr)
	if err != nil {
		return nil, err
	}
	iUserRepository := NewUserRepository(ctx, db)
	return iUserRepository, nil
}

func InitializeUserService(constr DBConnectionString, ctx context.Context) (UserService, error) {
	iUserRepository, err := InitializeUserRepository(constr, ctx)
	if err != nil {
		return UserService{}, err
	}
	userService := NewUserService(iUserRepository)
	return userService, nil
}
