// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package user

import (
	"context"
	"github.com/mtoku/di/app/infrastructure"
)

// Injectors from wire.go:

func InitializeUserRepository(constr infrastructure.DBConnectionString, ctx context.Context) (IUserRepository, error) {
	db, err := infrastructure.NewDB(constr)
	if err != nil {
		return nil, err
	}
	iUserRepository := NewUserRepository(ctx, db)
	return iUserRepository, nil
}

func InitializeInMemoryUserRepository() (IUserRepository, error) {
	iUserRepository := NewInMemoryUserRepository()
	return iUserRepository, nil
}
